version: '3.7'
services:
  db:
    image: postgres:17
    container_name: db_app
    env_file:
      - .env-non-dev
  
  test:
    image: test_image
    build: 
     context: . 
    container_name: test_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: ["/app/docker/app.sh"]
    ports:
      - 7777:8000