"""test data

Revision ID: 819a4b6da884
Revises: 1f1f39ed8d46
Create Date: 2025-02-10 23:29:54.257169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819a4b6da884'
down_revision: Union[str, None] = '1f1f39ed8d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        INSERT INTO bills (balance, user_id) VALUES 
        (0.0, 1),
        (0.0, 2);
        """
    )
    op.execute(
        """
        INSERT INTO users (full_name, email, role, hashed_password) VALUES 
        ('admin', 'admin@example.com', 'admin', '$2b$12$lyxUKBvT8NJudO2OVQ6IPO4FKB8bGNkZHc5F0g5QltQbdX00znzOa'),
        ('user', 'user@example.com', 'user', '$2b$12$H8neYqfy/HJ2XCtN1xeEr.nONN5aDR7ZPJRM.VbxysxwsYvz0Yrk2');
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
